          - name: installing docker
            yum:
                    name:
                            - docker
                    state: present

          - name: starting services
            service:
                    name: docker
                    state: started
                    enabled: yes
          - name: installing docker package
            pip:
                    name: docker
                    executable: pip3

          - name: yum repo for k8s
            yum_repository:
                     name: kubernetes
                     description: kubernetes
                     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                     enabled: yes
                     gpgcheck: yes
                     repo_gpgcheck: yes
                     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                     exclude: 
                          - kubectl
                          - kubelet
                          - kubeadm
          - name: installing k8s
            yum:
                    name:
                          - kubelet
                          - kubectl
                          - kubeadm
                    state: present
                    disable_excludes: kubernetes
          - name: starting kubelet service
            service:
                   name: kubelet
                   state: started
                   enabled: yes
          - name: changing driver
            copy:
                   dest: /etc/docker/daemon.json
                   content: |
                           {
                             "exec-opts": ["native.cgroupdriver=systemd"]
                           }
          - name: restarting docker service
            service:
                   name: docker
                   state: restarted
          - name: installing iproutetc
            yum:
                   name:
                         - iproute-tc
                   state: present
          - name: copying token file
            copy:
                    src: /tmp/token.sh
                    dest: /tmp/token.sh
          - name: applying token
            shell: " bash /tmp/token.sh"
